### ISSUE TITLE
Connect to Unreal over Subnet

### ISSUE THREAD

**Issue by arikrundquist** [PatrickPalmer/UnrealLiveLinkCInterface#1]
I am trying to use this wrapper to stream data between devices on my subnet. However, it seems that Live Link doesn't recognize sources created and streamed on another device. Is that something this library supports?

**Comment by PatrickPalmer** [comment]
This should be working for you.   I regularly use this library for streaming live link data from different machines to Unreal in a virtual production environment.  It should be noted that Live Link doesn't work in a packaged game and will only work in a development packaged game if you turn on networking via command line.

**Comment by PatrickPalmer** [comment]
Do you have some simple code to duplicate this? I've only used this on Windows.  What Unreal Engine version are you using?

**Comment by arikrundquist** [comment]
Thanks for the quick response! We're on 4.27.1, but I've been testing this for the last little bit and I think the issue is actually more a product of our network set up. Each of our machines are connected to multiple subnets via various network interfaces. By default, the Engine instance and CInterface instance each connect to a randomly chosen network interface. I found the setting in the Engine to listen on a particular NIC, but I'm not sure how to go about doing that on a system where the engine is not fully installed. Is there a way to programmatically define the interface to use through the wrapper, or some kind of configuration file we can manually set?

If not, I'm thinking about trying this at the top of `UnrealLiveLink_InitializeMessagingInterface` before the `UdpMessaging` module is loaded:
```
// expecting address_and_port as a c-string, ex. "10.1.4.9:5555"
if(address_and_port) {
    UUdpMessagingSettings* Settings = GetMutableDefault<UUdpMessagingSettings>();
    Settings->UnicastEndpoint = FString(ANSI_TO_TCHAR(address_and_port));
    Settings->SaveConfig();
}
```

Update: that code segment does not work. Running it before the module is loaded results in a segfault in `GetMutableDefault`, and running it after seems to have no effect even on subsequent runs.

**Comment by arikrundquist** [comment]
Looks like it might just have been a subnet issue... I'll do some more thorough testing tomorrow to make sure we have it consistently working on our side and then I'll mark this issue as closed.

**Comment by PatrickPalmer** [comment]
One thing that may help as well, you can either prioritize an interface or add a routing table entry.

**Comment by arikrundquist** [comment]
We got it, thanks for the help!
