### ISSUE TITLE
Missing  UnrealLiveLinkCInterfaceAPI.lib?

### ISSUE THREAD

**Issue by ein345** [PatrickPalmer/UnrealLiveLinkCInterface#2]
Is the example project missing UnrealLiveLinkCInterfaceAPI.lib file？

**Comment by PatrickPalmer** [comment]
The top level CMakeLists.txt file builds the static library:
                  https://github.com/PatrickPalmer/UnrealLiveLinkCInterface/blob/master/CMakeLists.txt#L7
Did this not build for you?

**Comment by ein345** [comment]
Later I found and built it. Thank you very much, this example gives me a lot.
